project:
  type: website

website:
  title: "Adrian's Generative Genomics Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog-posts/
        text: Blog Posts
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 3



